import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/providers/AuthProvider";
import { PostProvider } from "@/providers/PostContext";
import { ThemeProvider } from "@/providers/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Next Blog",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthProvider>
            <ThemeProvider>
                <html lang="en">
                    <body className={inter.className}>
                        <PostProvider>
                            <Toaster />
                            <Navbar />
                            {children}
                        </PostProvider>
                    </body>
                </html>
            </ThemeProvider>
        </AuthProvider>
    );
}
