import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import { ThemeProvider } from "@/providers/ThemeContext";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import AnimateProvider from "./template";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Next Blog",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthProvider>
            <ThemeProvider>
                <html lang="en">
                    <body className={inter.className}>
                        <Toaster />
                        <Navbar />
                        <AnimateProvider>{children}</AnimateProvider>
                    </body>
                </html>
            </ThemeProvider>
        </AuthProvider>
    );
}
